export const TEXT = {
  nav: {
    findJobs: 'Find Jobs',
    browseCompanies: 'Browse Companies',
    login: 'Login',
    postJob: 'Post a Job',
  },
  hero: {
    title: 'Discover more than 5000+ Jobs',
    subtitle: 'Great platform for job seekers that are passionate about startups. Find your dream job easier.',
    searchPlaceholder: 'Job title or keyword',
    locationPlaceholder: 'Select location',
    searchButton: 'Search my job',
    popular: 'Popular :',
  },
  sections: {
    showAllJobs: 'Show all jobs',
    companiesWeHelped: 'Companies we helped grow',
    featuredJobs: 'Featured jobs',
    exploreByCategory: 'Explore by category',
    latestJobsOpen: 'Latest jobs open',
  },
  categories: {
    design: 'Design',
    sales: 'Sales',
    marketing: 'Marketing',
    finance: 'Finance',
    technology: 'Technology',
    engineering: 'Engineering',
    business: 'Business',
    hr: 'Human Resource',
  },
  footer: {
    description: 'Great platform for job seekers that are passionate about startups. Find your dream job easier.',
    about: 'About',
    companies: 'Companies',
    pricing: 'Pricing',
    terms: 'Terms',
    advice: 'Advice',
    privacyPolicy: 'Privacy Policy',
    resources: 'Resources',
    helpDocs: 'Help Docs',
    guide: 'Guide',
    updates: 'Updates',
    contact: 'Contact',
    newsletter: 'Get job notifications',
    newsletterDescription: 'The latest job news, articles, sent to your inbox weekly.',
    emailPlaceholder: 'Email Address',
    subscribe: 'Subscribe',
  },
  dashboard: {
    overview: 'Overview',
    jobs: 'Jobs',
    applicants: 'Applicants',
    messages: 'Messages',
    settings: 'Settings',
    logout: 'Logout',
  },
  jobTypes: {
    fullTime: 'Full-time',
    partTime: 'Part-time',
    remote: 'Remote',
    contract: 'Contract',
    internship: 'Internship',
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    noResults: 'No results found',
    viewAll: 'View All',
    apply: 'Apply Now',
    learnMore: 'Learn More',
  },
  employerCta: {
    title: 'Start Hiring Today',
    subtitle: 'Post your jobs and connect with talented candidates',
    button: 'Sign Up For Free',
  },
} as const;
